### ISSUE TITLE
Uses wrong connection when ActiveRecord::Base uses MySQL

### ISSUE THREAD

**Issue by bf4** [ankane/pghero#107]
I got around this by adding an initializer:

```ruby
ActiveSupport.on_load(:active_record) do
  url = PgHero.config.fetch('databases').fetch('primary').fetch('url')
  PgHero::Connection.establish_connection url
  PgHero::QueryStats.establish_connection url
end
```

I'm not sure why PgHero::Database.connection was still using the mysql adapter, since the correct spec appeared to be passed into the establish_connection methods.

This resolves the error `SELECT command denied to user 'dev'@'localhost' for table 'pg_class'`

![screen shot 2017-02-06 at 12 26 39 pm](https://cloud.githubusercontent.com/assets/142914/22660652/fcba00a2-ec67-11e6-909f-d99305f9948f.png)

![screen shot 2017-02-06 at 12 26 50 pm](https://cloud.githubusercontent.com/assets/142914/22660579/b5fe808e-ec67-11e6-9645-c6694c38d30f.png)

![screen shot 2017-02-06 at 12 27 21 pm](https://cloud.githubusercontent.com/assets/142914/22660580/b600880c-ec67-11e6-89ef-b35d0bf3d182.png)

for completeness, our `config/pghero.yml` is

```yaml
default: &default
  databases:
    primary:
      url: <%= ENV.fetch('DATABASE_URL_POSTGRES_MASTER', 'postgresql://invalid/master') %>
    replica:
      url: <%= ENV.fetch('DATABASE_URL_POSTGRES_SLAVE', 'postgresql://invalid/slave') %>

development:
  <<: *default

production:
  <<: *default
```
