### ISSUE TITLE
Unable to setup multiple bases

### ISSUE THREAD

**Issue by ced75** [ankane/pghero#118]
Hi,

I have installed pghero package under Linux (Ubuntu 14.04).

I configured a single database like this:
```
sudo pghero config:set DATABASE_URL=postgres://user1@172.19.0.8:5432/db1
sudo service pghero restart
```
It works.

If I change the database like this:
```
sudo pghero config:set DATABASE_URL=postgres://user2@172.19.0.2:5432/db2
sudo service pghero restart
```

It also works.

Then, I try multiple databases configuration.
Here is my pghero.yml file:
```
test:
  databases:
    db1:
      url: postgres://user1@172.19.0.8:5432/db1
    db2:
      url: postgres://user2@172.19.0.2:5432/db2
```

Then I perform:
```
cat pghero.yml | sudo pghero run sh -c "cat > config/pghero.yml"
sudo service pghero restart
```
But when I go in the PgHero Overview, I still see only one database (the last one I configured alone).
What am I doing wrong?

Thanks in advance for your help.
