### ISSUE TITLE
insufficient privilege when connecting a Heroku follower

### ISSUE THREAD

**Issue by gaaady** [ankane/pghero#221]
Hi,
I deployed pghero to Heroku and attached a second follower DB to pghero using:
```
databases:
  staging:
    url: <%= ENV["PGHERO_DATABASE_URL"] %>
  production_follower:
    url: <%= ENV["HEROKU_POSTGRESQL_BLUE_URL"] %>
```

when launching pghero and choosing the production_follower from Databases i see under queries:

> insufficient privilege

How can I connect a follower DB to PGhero?

Thanks!
