### ISSUE TITLE
ActiveRecord::AdapterNotSpecified (database configuration does not specify adapter):

### ISSUE THREAD

**Issue by luizkowalski** [ankane/pghero#23]
I have a `database.yml` as following:

```
production:
  adapter: postgresql
  encoding: unicode
  database: database_production
  pool: 5
```

when I try to access /pghero, I see the error on title. Did I missed something?
