### ISSUE TITLE
Multiple databases in the same rds instance

### ISSUE THREAD

**Issue by vivekanandg** [ankane/pghero#236]
Hi,

If I want to monitor different dbs in the same rds instance, do I have to create pg_stat_statements and exec [this](https://github.com/ankane/pghero/blob/master/guides/Permissions.md) in each of them? 
Or is there a better way?

**Comment by ankane** [comment]
Yeah, you'll need to do that in each of the databases. You also want to let PgHero know they are part of the same instance to make sure stats are captured correctly.

```yml
databases:
  db1:
    url: postgres://...
  db2:
    url: postgres://...
    capture_query_stats: db1
```
