### ISSUE TITLE
[help] Runnig pghero inside k8s with a url prefix

### ISSUE THREAD

**Issue by psykidellic** [ankane/pghero#309]
Please let me know if there is a better place for this question.

We have k8s based app which is available at "/". I would like to add pghero to the setup and make it available at "/pghero". I have been able to setup the right deployment and service file and everything works. This is the ingress file I am using

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-app
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress-pghero
spec:
  rules:
  - host: mydomain.com
    http:
      paths:
      - backend:
          serviceName: pghero
          servicePort: 8080
        path: /pghero(/|$)(.*)
  tls:
  - hosts:
    - mydomain.com
    secretName: nginx-app-certs
```

With this setup, I can get the index page to load up but unfortunately, there is an issue loading up any of the asset file.

It seems to then request all assert url at:

```/assets/pghero/application-d8f1d0e17e1ff16be2916423ef4c384396f0ecf0669de887c1cafadaa9fc233d.css```

which results in 404 as we have no ingress for that rule.

If I forcefully request the url as 

```/pghero/assets/pghero/application-d8f1d0e17e1ff16be2916423ef4c384396f0ecf0669de887c1cafadaa9fc233d.css``` it works as the ingress rewrite will then change to correct /asserts/pghero where the app is able to route it correctly.

Any idea why is it trying to request `/asserts/pghero/xxx` instead of `/pghero/asserts/xxxx`? Is there some other trick, I can do to make this work.
