### ISSUE TITLE
docker-compose stats question

### ISSUE THREAD

**Issue by Dulanic** [ankane/pghero#327]
So I thought I was doing it right, but Im not seeing anything from the query history outside of pgadmin and pghero queries...  Maybe my docker-compose command is wrong?  I was trying to do a PR (https://github.com/ankane/pghero/pull/324) to explain better how to capture stats and table size... table size seems to be working, but the query portion isn't capturing most of the queries?

EX: I run this 10 times, all are 300+ms... but I dont see this in my data when I check...

![image](https://user-images.githubusercontent.com/2948206/87252926-71875d80-c43c-11ea-9885-c557dad907b0.png)

This is the command Im running, maybe I need to change this? It runs and lists all of my DBs as expected... and I am seeing other queries for other DBs, but not for this one?
```docker-compose run -e DATABASE_URL=postgres://user:pw@ipaddr/postgres pghero bin/rake pghero:capture_query_stats```

When I query the table,, this is all I'm seeing and it didn't capture the queries I ran in the first SS?

![image](https://user-images.githubusercontent.com/2948206/87252930-79470200-c43c-11ea-9833-fd1abf538d49.png)

This is my .sh I run as a cron job to capture every 5 minutes.. I prune after since this creates a new container every time its run.

```#!/bin/bash
cd /opt
docker-compose --env-file /opt run pghero bin/rake pghero:capture_query_stats
docker system prune -f
```

![image](https://user-images.githubusercontent.com/2948206/87253050-9c25e600-c43d-11ea-9342-0d866f6ab52c.png)

docker-compose.yml
```
  pghero:
    image: ankane/pghero
    container_name: pghero
    restart: unless-stopped
    ports:
      - 8087:8080
    environment:
      TZ: America/Chicago
      PGHERO_STATS_DATABASE_URL: postgres://redacted@database/postgres
    volumes:
      - /mnt/ssd/docker/containers/pghero/pghero.yml:/app/config/pghero.yml
```
pghero.yml
```databases:
  main:
    url: postgres://redacted@database/postgres
  tesla:
    url: postgres://redacted@database/teslamate
  nextcloud:
    url: postgres://redacted@database/nextcloud
  homeassistant:
    url: postgres://redacted@database/homeassistant```

**Comment by ankane** [comment]
Hey @Dulanic, I think the issue might be due to the fact that all the databases are part of the same Postgres instance. When query stats are captured for the first database, they're reset across the entire instance (since it's not possible to reset for a specific database). You can get around this with:

```yml
  main:
    url: postgres://redacted@database/postgres
  tesla:
    url: postgres://redacted@database/teslamate
    capture_query_stats: main
  nextcloud:
    url: postgres://redacted@database/nextcloud
    capture_query_stats: main
  homeassistant:
    url: postgres://redacted@database/homeassistant
    capture_query_stats: main
```

Which tells PgHero to capture all the stats at once with the main instance. Let me know if that solves it.

**Comment by Dulanic** [comment]
Thanks, I'll try that in the morning and will let you know. I didn't know the capture could be put in the pghero yml.

**Comment by ankane** [comment]
Added it to the docs. Also, it looks like it's possible to reset query stats on a finer granularity in Postgres 12+, so will look into adding that.

**Comment by bheemreddy181** [comment]
I also see the same issue but in my case databases are from different Postgres instance, I don't see `a time range slider will appear on the Queries tab.` after running capture query stats

**Comment by Dulanic** [comment]
Working as expected now, thank you for that.

**Comment by Dulanic** [comment]
@bheemreddy181 you may want to make sure you still keep the  DATABASE_URL: in the docker-compose.yml.

**Comment by bheemreddy181** [comment]
@Dulanic what if I have multiple Postgres instances?

**Comment by Dulanic** [comment]
@bheemreddy181 

My docker-compose.yml: I have the database_url env variable set like so, postgres is the database I am using to store the history.

```DATABASE_URL: postgres://user:pw@ipaddr/postgres```

My pghero.yml is where the multiple DBs are delcared as mentioned above.

```
  main:
    url: postgres://redacted@database/postgres
  tesla:
    url: postgres://redacted@database/teslamate
    capture_query_stats: main
  nextcloud:
    url: postgres://redacted@database/nextcloud
    capture_query_stats: main
  homeassistant:
    url: postgres://redacted@database/homeassistant
    capture_query_stats: main
```
