### ISSUE TITLE
[Question ]: Capture query stats

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/pghero#346]
Hey,

Can we run capture query stats this way 

```
docker run -v /etc/docker-compose/pghero.yml:/app/config/pghero.yml \
        ankane/pghero bin/rake pghero:clean_query_stats
```
we are actually mounting our own pghero.yml which has all the database config needed something like below

```
databases:
  main:
    url: <%= ENV["MAIN_URL"] %>
primary:
    url: <%= ENV["PRIMARY_URL"] %>
```
Each DB stays on its own host
