### ISSUE TITLE
pghero docker timezone

### ISSUE THREAD

**Issue by Dulanic** [ankane/pghero#367]
Would it be possible to add a TZ variable for the docker containers? Or am I missing some setting that I can change? I'd like it to be my local TZ vs UTC. I tried mounting /etc/localtime and /etc/timezone, but neither fixes it. Allowing a TZ env variable could be easily implemented within the dockerfile, I'd submit a PR, but I don't know where your dockerfile is not in this repo.

https://wiki.alpinelinux.org/wiki/Alpine_setup_scripts#setup-timezone

**Comment by ankane** [comment]
Hey @Dulanic, there's currently an option in Rails (`PgHero.time_zone`), but would be good to add an environment variable for Docker. Can probably do something similar to `show_migrations`: https://github.com/pghero/pghero/blob/bc633c680d87408b69f658c59f545e9e4f19b622/config/application.rb#L53

**Comment by Dulanic** [comment]
Thanks, that makes sense. So I haven't worked /w Rails. I am OK /w docker python etc... so my question is, where is the dockerfile you use? I'd be happy do edit to setup a TZ env variable etc..., but I'm not sure where in the rails files that env variable would be pulled in. 

Or are you saying I set the TZ in the container by just adding a TZ env variable in my docker run command then just adding this would work?

`PgHero.time_zone = ENV["TZ"] `

This is my current docker-compose setup.
```
 pghero:
    image: ankane/pghero:latest
    container_name: pghero
    environment:
      TZ: $TZ
      DATABASE_URL: $DB_URL
    volumes:
      - ./pghero/pghero.yml:/app/config/pghero.yml:ro
    restart: unless-stopped
```
