### ISSUE TITLE
Multiple Databases GUI

### ISSUE THREAD

**Issue by encryptblockr** [ankane/pghero#391]
How does the GUI looks like for managing multiple databases?

I have a multi database setup but i have no screenshot to compare against
I don't see any error but i only see the first and primary database only, same as the UI for single database

**Comment by ankane** [comment]
Hey @encryptblockr, there will be a list of databases on the left side.

![multiple-dbs](https://user-images.githubusercontent.com/220358/132631164-8c8d03c4-14cb-4c4b-b5c3-1382fcb62e07.png)

**Comment by encryptblockr** [comment]
i am not seeing the `Databases` section. Can you please help with what i have wrong?
Here is my `pghero.yml`


```
databases:
  database1:
    url: <%= ENV["DATABASE_URL"] %>
  database2:
    url: <%= ENV["DATABASE_URL_V2"] %>
  database3:
    url: <%= ENV["DATABASE_URL_V3"] %>
```


and the for the `env`s

```
DATABASE_URL=postgres://db_user:db_password@database1:5432/db_db
DATABASE_URL_v2=postgres://db_user:db_password@database2:5432/db_db
DATABASE_URL_v3=postgres://db_user:db_password@database3:5432/db_db
```

the only one that shows up like a single database in pghero is the `database1`...nothing else shows
what am i doing wrong?
