### ISSUE TITLE
Docker pghero.yml and NullDB

### ISSUE THREAD

**Issue by afterdesign** [ankane/pghero#417]
I'm using docker image. I've create Dockerfile where I copy the `pghero.yml`.

Running `pghero:capture_space_stats` and `pghero:capture_query_stats` works without any problems but for `pghero:clean_space_stats` I have to set `DATABASE_URL` env var as it's throwing `NullDB not configured. Require a framework, ex 'nulldb/rails'`.

I started to debug this and it looks databases have proper URLs but here it throws the error:
```
      def clean_space_stats
        PgHero::SpaceStats.where(database: id).where("captured_at < ?", 90.days.ago).delete_all
      end
```

The `pghero.yml` I'm using looks like this:

```
databases:
  db_1:
    url: postgres://<%= ENV["USER"] %>:<%= ENV["PASSWORD"] %>@<%= ENV["HOST"] %>:5432/db_1
  db_2:
    url: postgres://<%= ENV["USER"] %>:<%= ENV["PASSWORD"] %>@<%= ENV["HOST"] %>:5432/db_2
    capture_query_stats: db_1
  db_3:
    url: postgres://<%= ENV["USER_2"] %>:<%= ENV["PASSWORD_2"] %>@<%= ENV["HOST_2"] %>:5432/db_3
```
