### ISSUE TITLE
`the scheme postgresql does not accept registry part` when running historical data db in the same docker-compose

### ISSUE THREAD

**Issue by baptisteArno** [ankane/pghero#427]
Hi,

I configured a docker-compose to also instantiate the historical stats database:

```yml
version: "3.3"

services:
  pghero_historical_db:
    image: postgres:12
    restart: always
    volumes:
      - .stats-data:/var/lib/postgresql/data
      - .db-entrypoint:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pghero:
    image: ankane/pghero
    container_name: "pghero"
    depends_on:
      - historical_db
    env_file: ".env"
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pghero.loadBalancer.server.port=8080"
      - "traefik.http.routers.pghero.rule=Host(`pghero.${BASE_DOMAIN}`)"
      - "traefik.http.routers.pghero.entrypoints=websecure"
      - "traefik.http.routers.pghero.tls.certresolver=myresolver"
      
```

I'm attempting to connect to the following history db url: `postgresql://postgres:postgres@pghero_historical_db:5432/postgres`

But I'm getting this error on container launch:

```
URI::InvalidURIError (the scheme postgresql does not accept registry part: postgres:postgres@pghero_historical_db:5432 (or bad hostname?))
```
